### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by loudnate** [loudnate/Loop#109]
Color needs some re-thinking. Most urgently, green can't represent both "insulin" and "good/fresh". 
In addition, indicators like battery and reservoir don't need to take visual precedence when they're "in the green" anyway. They should move to the background when all is well, using a grey tone that still indicates level. 

Where green/yellow/red is used, there should be another distinguishing glyph to assist those with colorblindness. A red circle with an exclamation point would better indicate a stale loop.

**Comment by loudnate** [comment]
The other thing about color is that the graphs rely too much on color for distinguishing data type. It's time to increase white space (and add labels). All 4 graphs don't need to fit on the same screen simultaneously, since it's possible to pan values while scrolling.

**Comment by jlucasvt** [comment]
Just a note.  It may also be beneficial when to change the Prediction color to highlight the prediction as distinctive from the overall Glucose history.

**Comment by jlucasvt** [comment]
Not sure if the charting lib would support it, but how about a means of sorting the layered chart data using a tab interface that allows the selection of Glucose, Insulin, Dosing, Carbs.  
![image](https://cloud.githubusercontent.com/assets/19819388/17482098/3a8e77c2-5d4e-11e6-83d1-d3e0dad2f326.png)

**Comment by eszcloud** [comment]
For prediction, one alternative to having a different color for historical vs predicted data would be to have the one set of values be bolder than the others both in the plot and for the numbers as you're panning through.
