### ISSUE TITLE
High temp recommended after carb entry and bolus

### ISSUE THREAD

**Issue by dm61** [loudnate/Loop#120]
When a user enters carbs and delivers a bolus, a high temp immediately shows up as recommended. I believe this is because the meal is immediately taken into account by the Loop calculations, while the bolus is not, because the Loop relies solely on actual pump data to calculate IOB (as it should). This would not normally be an issue, as the Loop would become aware of the bolus delivered on the next pump readout. However, the high temp recommendation could become problematic if the user accepted the recommended high temp _and_ if the Loop, for whatever reason, failed to communicate with the pump just after that. The user could be left with the bolus and the high temp for 30 min (effectively a double bolus) - a potentially hazardous situation.

**Comment by loudnate** [comment]
As @jlucasvt mentioned, this is an issue of displaying a "recommended temp" based on carb delivery but before the bolus has been confirmed as delivered. No temporary basal is enacted at that stage.

I do think it's important to fix this by not displaying the recommended temp to avoid confusion. Thank you for filing.
