### ISSUE TITLE
Issues polling glucose from Share

### ISSUE THREAD

**Issue by loudnate** [loudnate/Loop#13]
@channemann and @eyim are having intermittent issues with glucose updating from Share.

Asking them to debug invocations of `private func backfillGlucoseFromShareIfNeeded()`. If the issue isn't immediately reproducible, additional remote logging calls can be added.

**Comment by loudnate** [comment]
Looks like @channmann is seeing `DataError`. We need to augment ShareClient to find out what the core issue is. 

https://github.com/mddub/dexcom-share-client-swift/issues/3

**Comment by channemann** [comment]
Situation:

- Was playing softball, left phone, receiver, and RL on sideline, drifted in and out of range starting around 11 am
- Receiver (and share app) show periodic glucose readings received between 11 am and 12:35 pm, at which point I was back in range and getting consistent readings
- Loop app has reservoir data until 11:05 am, then picks back up at 12:30 (and has reservoir data every 5 minutes after that)
- Loop app stops showing glucose data after11:04 am
- Error from mLab:

```{
    "_id": {
        "$oid": "57532eb2c2ef1612e2a11d6e"
    },
    "source": "ShareClient",
    "message": "DataError(\"Failed to decode SGVs as array: {\\\"Code\\\":\\\"SessionNotValid\\\",\\\"Message\\\":\\\"Error in the application.\\\",\\\"SubCode\\\":\\\"<OnlineException DateThrownLocal=\\\\\\\"2016-06-04 12:40:33.7290426-07:00\\\\\\\" DateThrown=\\\\\\\"2016-06-04 19:40:33.7290426+00:00\\\\\\\" ErrorCode=\\\\\\\"\\\\\\\" Type=\\\\\\\"6\\\\\\\" Category=\\\\\\\"5\\\\\\\" Severity=\\\\\\\"1\\\\\\\" TypeString=\\\\\\\"SessionNotValid\\\\\\\" CategoryString=\\\\\\\"Logical\\\\\\\" SeverityString=\\\\\\\"Minor\\\\\\\" HostName=\\\\\\\"\\\\\\\" HostIP=\\\\\\\"\\\\\\\" Id=\\\\\\\"{C6EFDB18-A1D8-46D7-97F4-39D82F1B3E41}\\\\\\\" Message=\\\\\\\"Error in the application.\\\\\\\" FullText=\\\\\\\"Dexcom.Common.OnlineException: Error in the application.\\\\\\\" \\\\/>\\\",\\\"TypeName\\\":\\\"FaultException\\\"}\")",
    "reportedAt": "2016-06-04T12:40:33-0700"
}```

**Comment by loudnate** [comment]
Can you open a new ticket here: https://github.com/mddub/dexcom-share-client-swift/issues? It looks like we need to detect and renew session expiry.

**Comment by mddub** [comment]
Give v0.1.2 of https://github.com/mddub/dexcom-share-client-swift a try, let's see if that fixes it.
