### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by rdraeger** [loudnate/Loop#133]
Getting the following:

/Users/riandraeger/Library/Developer/Xcode/DerivedData/Loop-dtxjtygpwjqtvpdpviclkilopvcs/Build/Intermediates/Loop.build/Debug-iphoneos/Loop.build/Script-43EDDBEF1C361BCE007D89B5.sh: line 3: /usr/local/bin/carthage: No such file or directory

**Comment by ps2** [comment]
You need to install carthage. https://github.com/loudnate/Loop#installing-carthage

**Comment by rdraeger** [comment]
Thanks!
