### ISSUE TITLE
Incorrect "since" time for total insulin

### ISSUE THREAD

**Issue by channemann** [loudnate/Loop#134]
![image](https://cloud.githubusercontent.com/assets/5387400/18011549/8603dcea-6b6a-11e6-91c9-4388d15dfb15.png)

It appears that the time displayed for total insulin (normally for the day since approximately midnight) had a bug.

**Comment by loudnate** [comment]
This is fixed in LoopKit here: https://github.com/loudnate/LoopKit/commit/559ead5bbc3103648b00918cd527c95bee131d89#diff-f15dc05fbeb2566c8342d34c44f52529R796

Will be included in the next Loop release.
