### ISSUE TITLE
Loop seems to do the wrong thing when reservoir reports 0

### ISSUE THREAD

**Issue by beached** [loudnate/Loop#142]
It is known that there is give or take 10 units after the reservoir reports 0 units left.  But loop looks like it assumes no delivery while insulin is being delivered and increases the dose.  I think the safest bet is to either listen for the no delivery alert or to assume delivery and disable looping until the reservoir is changed.

I just noticed while dropping 0.7units/5min(around 7mmol/L at the time), no carb on board, at was dosing 3.4u/hr when I normally take 1.2u/hr at that time.  

Almost looks like a feedback loop.

**Comment by loudnate** [comment]
This is fixed here: https://github.com/loudnate/Loop/pull/146
cc: @sarahspins
