### ISSUE TITLE
Different low target vs. bolus ranges

### ISSUE THREAD

**Issue by ddaniels1** [loudnate/Loop#157]
As has been brought up before, eating with a blood sugar of 80 and bolusing for the impending rise is perfectly reasonable, but one may not want to target range set that low. As currently configured Loop won't suggest a bolus unless at or predicted to be above the lower limit of the target range.  

How about a configurable feature which allows one to bolus if >/= (lower limit of target range -20 mg/dl).  That way one can set the target range 100-120 mg/dl and still bolus even if currently at 80.    Would agree for multiple reasons that if at 100 and predicted to be < 100  in the future, even with currently entered carbs, one should not have a bolus suggestion.  We can imagine this in the situation in which carbs are being used to prevent a low as suggested in #156

**Comment by jlucasvt** [comment]
@ddaniels1.  The Bolus Wizard suggestion on Future Glucose Prediction from Carb entry is easily modified in the codebase.  A number of individuals have done so very successfully.  The current implementation is a safety feature, however you can change this in your fork or codebase directly very easily.

**Comment by ddaniels1** [comment]
@jlucasvt , I'm not a programmer, but l want to learn SWIFT as I had to learn linux command line to set up openaps for Olivia.  Can you point me in the right direction?

**Comment by loudnate** [comment]
I'm not sure the complexity of necessary configuration is worth the benefit it would bring. Which would be the target BG used for the bolus suggestion? And most importantly, how would you communicate that to users?

**Comment by ddaniels1** [comment]
I would say anything above 80 it would suggest a bolus. Alternative is to set the target range 80-120.  On openaps we were setting the range 110-120 to allow some wiggle room for low temping to work before becoming hypo.
