### ISSUE TITLE
Display of mmol/L units 

### ISSUE THREAD

**Issue by beached** [loudnate/Loop#159]
It looks like Loop is trying to display too many digits for mmol/L.  Only 3 are ever needed at most.  Actually , when the pump reports a bg <=99mg/dl only 2 are needed( so <=5.5mmol/L)  but for consistency 3 is usually fine.

As one can see, this causes formatting bugs
![bg display](https://cloud.githubusercontent.com/assets/855156/18252868/ff94d482-735e-11e6-8eb0-e8a2d4efc5cc.jpg)

Seeing as the data from the pump expresses the info in mg/dl and generally has 3 significant digits this could be accomplished with a formatting flag of  %.1f

**Comment by beached** [comment]
I am testing the use of 
```
numberFormatter.usesSignificantDigits = true
numberFormatter.minimumSignificantDigits = 2
numberFormatter.maximumSignificantDigits = 3
```
To format the glucose hud display.

**Comment by loudnate** [comment]
Thanks – the NSNumberFormatter significant digits setting is exactly how I planned to fix these cases.

The screenshots are really helpful. Please add any more where things aren't correct to this ticket!

**Comment by beached** [comment]
I was thinking that maybe, excuse my swift, but a member of the HKUnit that formats blood glocose for a subtype of sorts that does it.  then any string for a glucose uses that.

**Comment by loudnate** [comment]
Yeah, that's what's existed here: https://github.com/loudnate/LoopKit/blob/master/LoopKit/HKUnit.swift#L21-L28

**Comment by beached** [comment]
So that fixed the issue in issue in the glucosehud.  Not the graphs or other areas.
![fixed](https://cloud.githubusercontent.com/assets/855156/18259570/5f9e9c06-73b3-11e6-81ef-ad9dc34b3ae2.png)

**Comment by beached** [comment]
Looks like the retrospective correction screen is hardwired to mg/dl
![image](https://cloud.githubusercontent.com/assets/855156/18602637/dab61cec-7c38-11e6-8ee8-bba07449ec72.png)

**Comment by beached** [comment]
Actually, I am wrong,  it does eventually but the scale is off
![image](https://cloud.githubusercontent.com/assets/855156/18602676/1ebcaaaa-7c39-11e6-93ad-0de806dcd7fc.png)

**Comment by beached** [comment]
The units updated after checking/unchecking
