### ISSUE TITLE
Nightscout Integration regression

### ISSUE THREAD

**Issue by beached** [loudnate/Loop#161]
I cannot see why, but since 0.11.1 the temp basal data sent to nightscout does not show up in the basal display or basal pill.  I think it is related to history upload but cannot see the relevant change in the patches.

I have re-tested with 0.11.0 and 0.10.1 and it works there.

**Comment by ps2** [comment]
Can you see if the temp basal events are making to your Event History in Loop?  And then check to see if they're making it to treatments.json in NS?

**Comment by beached** [comment]
I will try that later.  Also, this looks related too, but it is from 0.11.0
![basal pill](https://cloud.githubusercontent.com/assets/855156/18256308/92b49da2-7381-11e6-9218-609731446b14.jpg)
![loop pill](https://cloud.githubusercontent.com/assets/855156/18256309/95da238a-7381-11e6-83c3-d351c856adfd.png)

They are coming from different data sources at different times

**Comment by ps2** [comment]
That's a different issue; NS calculates IOB differently than Loop. I haven't looked into the details, but you should probably disable the IOB plugin, and use what Loop is telling you.

**Comment by beached** [comment]
The first image is the Basal pill, not IOB.  But yeah, I rarely look at IOB anyways.

**Comment by ps2** [comment]
I can confirm this issue. Looking in to it.

**Comment by ps2** [comment]
Odd, since Riley is running 0.11.0 + https://github.com/loudnate/Loop/pull/153, and it's working fine.

**Comment by beached** [comment]
This is 11.0 and working, going to 11.1 the basal pill never( or rarely, not sure if it does eventually) shows the temp basal data on the basal pill side

**Comment by dm61** [comment]
I am looking at two Loops, both at 0.10.1, The one with a 523 pump has worked fine, including NS integration. The other, with a 723 pump, worked fine for a few days, and has then lost pump history items on NS. I've planned to upgrade both to 0.11.1 today, but will probably wait some more - looks like there may be some issue with pump history upload to NS even on 0.10.1.

**Comment by ps2** [comment]
I'm seeing temp basal pairs where the duration is first getting passed to NightscoutUploader.upload().  I'm thinking this change is likely the culprit: https://github.com/loudnate/LoopKit/compare/v0.6.0...v0.7.0#diff-f15dc05fbeb2566c8342d34c44f52529R644 @loudnate, I think I'll make the uploader code not dependent on order, and just look for paired (in time) records.

**Comment by loudnate** [comment]
@ps2 that change was paired with
https://github.com/loudnate/Loop/commit/2c62c17fff3a9e6eb2b81927fb00df86c33fac12#diff-e49b73a75143263adce7ce2d8d0f763aL846

**Comment by loudnate** [comment]
@ps2 Is the order of the pairs random? Or consistent?

**Comment by loudnate** [comment]
Short-term, it might be easier to just revert those commits. Long-term, there's no need to do the double-work of temp basal matching.

**Comment by ps2** [comment]
Right now, on 0.11.1, as new temp basals are enacted and fetched from history, when I put a breakpoint on the call to uploader.upload(), I see that the TempBasalDurationPumpEvent records are consistently before the TempBasalPumpEvent records. 

Consistent as in 4 stops in the debugger confirmed this.  I did have a history mis-fetch while watching, and when all four events were passed to the upload, one temp basal NS treatment made it up (from pairing a rate with the wrong duration record). 

Your two changes (one reversing, and the other backing out a reverse) seems like they would cancel each other out, but I suppose it depends on what happens in the fetch sorting with events that have the same timestamp.

**Comment by ps2** [comment]
The mis-pairing is another reason to update the ns uploading code to be more resilient, and not to assume one follows the other.

**Comment by ps2** [comment]
Where those commits fixing some other issue?

**Comment by loudnate** [comment]
No, they were just seeking a more semantic behavior. It seems like after
date, the auto-increment ID (internal to CoreData) is used.

I think an upload interface that allows the client to populate NS events
rather than using the fragile pump history is probably most resilient for
the long-term. This is already partially what's necessary for adding HK
carbs.

**Comment by ps2** [comment]
yes, that sounds like an improvement

**Comment by loudnate** [comment]
I'll prepare to revert those two lines.

**Comment by loudnate** [comment]
@ps2 please open a PR against `master`.
