### ISSUE TITLE
Visual issue bolus screen on v0.12

### ISSUE THREAD

**Issue by beached** [loudnate/Loop#174]
Since v0.12.0 the bolus entry green is started vertically with a negative offset such that only the deliver button is visible.  After scrolling down one cannot return to this state and it becomes normal.
![image](https://cloud.githubusercontent.com/assets/855156/18617904/83117ec4-7da9-11e6-8791-dae90539d836.png)

**Comment by jlucasvt** [comment]
I have the same issue iPhone 6s , MM722, iOS 9.3.5, Loop v0.12.0.  

On my deployment the issue is repeatable even after scrolling down.  Debug console states..

``Can't find keyplane that supports type 8 for keyboard iPhone-Portrait-DecimalPad; using 4131139949_Portrait_iPhone-Simple-Pad_Default``

**Comment by loudnate** [comment]
> Debug console states the following when activated..

this message is unrelated to the visual issue.
I'm not seeing the issue on iOS 10. Sounds like this is just a visual quirk and not a serious usability concern?

**Comment by beached** [comment]
This is iOS 9.3 here.  I'll upgrade and see.  I'm on an iphone SE

**Comment by beached** [comment]
Loop 0.12.0 release on iphone SE with iOS 10 has same issue.  Maybe some assumption on screen size?

**Comment by jlucasvt** [comment]
The issue presents itself only when using a " Zoomed" Display Zoom Setting.
iOS Settings > Display & Brightness > View > Standard  = No Issues 
iOS Settings > Display & Brightness > View > Standard  = Issue Presents itself.

**Comment by beached** [comment]
On iPhone SE I do not see a zoomed setting.
