### ISSUE TITLE
Labels on status screen graphs.

### ISSUE THREAD

**Issue by ps2** [loudnate/Loop#180]
It took me a while to know which graph was insulin and which was carbs.  Our school nurse has expressed confusion about it as well as my parents.  In my experience, it's a nearly universal response.

The consistent color coding is a step in the right direction, but maybe not sufficient.

**Comment by loudnate** [comment]
Thanks for re-filing this. It's on my list, [and mentioned it here](https://github.com/loudnate/Loop/issues/109#issuecomment-238111705) but needed the bump back up.

**Comment by jlucasvt** [comment]
I had done a label overlay on each graph at the upper left when I started using Loop to help me remember.  I am sure there is a much better way to accomplish the same thing using the the chartkit.

![13782237_10153871460591523_8838772967175206979_n](https://cloud.githubusercontent.com/assets/19819388/18795842/6cb4cf7a-8194-11e6-8189-fef6f39a8572.jpg)

**Comment by channemann** [comment]
Those look pretty good! One thought is to push them to the upper right. Glucose should be trending towards the target range, there will be no doses in the future, and both IOB and COB will taper to zero, meaning that the label shouldn't interfere with data.

-----
Chris Hannemann
chris.hannemann@gmail.com

**Comment by jlucasvt** [comment]
I tried the upper right initially, but my typical use case always led to the labels being obscured by the data readout.  I also used verbose labels to get the concepts to stick in my head instead of Acronyms so this may be part of my issue.  Longer text may be useful for the "school nurse" use case.
