### ISSUE TITLE
Open appropriate Dexcom app

### ISSUE THREAD

**Issue by channemann** [loudnate/Loop#20]
Currently, a single tap on the status screen's glucose chart opens the Dexcom G5 app. If the user is instead using a G4, is would to preferable to open the G4 app (Share 2).

**Comment by loudnate** [comment]
Do you know what the URL scheme is to open the G4 app?

**Comment by channemann** [comment]
I do not; is this something you can only find by examining the source code,
or is it publicly exposed?

On Mon, Jun 6, 2016 at 11:25 AM, Nathan Racklyeft <notifications@github.com>
wrote:

> Do you know what the URL scheme is to open the G4 app?
>
> > On Jun 6, 2016, at 10:36 AM, Chris Hannemann <notifications@github.com>
> wrote:
> >
> > Currently, a single tap on the status screen's glucose chart opens the
> Dexcom G5 app. If the user is instead using a G4, is would to preferable to
> open the G4 app (Share 2).
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/loudnate/Loop/issues/20#issuecomment-224044833>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFI0iDqkzh7u-PWrEmci5TuOKSqJ39Dnks5qJGYJgaJpZM4IvImH>
> .
>



-- 
Chris Hannemann
chris.hannemann@gmail.com

**Comment by loudnate** [comment]
It's available in the plist file in the encrypted binary package downloaded by iTunes. Find the ipa file in finder, rename it to .zip, and uncompress it. Find the bundle in the Payload directory, and open it using the "Show Package Contents" context menu option. Inside there should be a file called Info.plist, and any supported URL schemes are under the CFBundleURLSchemes key.

**Comment by channemann** [comment]
I don't see the CFBundleURLSchemes key, but under URL types > Item 0, there is `URL identifier` of `com.dexcom.Share2`. Is that what is needed?

Info.plsit file is attached, though I had to zip it to upload it here.

[Info.plist.zip](https://github.com/loudnate/Loop/files/301220/Info.plist.zip)

**Comment by loudnate** [comment]
It's there: `dexcomshare`

**Comment by loudnate** [comment]
Would you be interested in making this change? You can copy the logic that already exists and add an `else if` condition. You'll also need to add the scheme to the `LSApplicationQueriesSchemes` array in Loop's `Info.plist`.

**Comment by channemann** [comment]
I can give it a shot. Am I right that the conditional would be here:

https://github.com/loudnate/Loop/blob/master/Loop/View%20Controllers/StatusTableViewController.swift#L561

In which case, how do I determine whether the user has a G4 or G5? I actually have both apps on my phone, so it successfully goes to the G5 apps even though I have no reason to be there right now.

**Comment by loudnate** [comment]
well then I'd suggest you delete the G5 app from your phone if you're not using it 😄 
I'd rather keep the logic simple rather than digging in the device configuration from the status screen and say:
```pseudocode
IF (G5 app installed) THEN open(G5 app)
ELSE IF (G4 app installed) THEN open(G4 app)
```

You can use the `canOpenURL` method in each `if` condition:
`if let URL = NSURL(string: "dexcomcgm://") where UIApplication.sharedApplication().canOpenURL(URL)`
