### ISSUE TITLE
Backfill data from Share servers

### ISSUE THREAD

**Issue by channemann** [loudnate/Loop#21]
Due to bluetooth dropping between the phone and the Dexcom receiver, as well as other connectivity issues, the most recent glucose data isn't always uploaded to the Share servers when Loop goes to retrieve it. While this cannot be solved for the present loop cycle, the failed retrieval has impacts on the follow-on cycles as well, specifically regarding prediction calculations. A method for backfilling missing data from the Share servers would fix this.

How many data points to backfill is an open question, but probably at least the last 15 minutes.

**Comment by loudnate** [comment]
Step 1: https://github.com/loudnate/LoopKit/issues/33

**Comment by loudnate** [comment]
Step 2: https://github.com/loudnate/LoopKit/pull/36
