### ISSUE TITLE
History decoding

### ISSUE THREAD

**Issue by loudnate** [loudnate/Loop#24]
@ps2 I think I can meet you in the middle here.

**Comment by ps2** [comment]
I'm sure we can.  You're right that uploading should be separated from history fetching... Just haven't figured out what that looks like exactly.

**Comment by loudnate** [comment]
I've got a vision for how history gets into InsulinKit in a way that's compatible with 22&23 pumps. I'm going to keep working and CC'ing you in this branch/milestone. Please don't hesitate to give feedback.

**Comment by ps2** [comment]
The 0.4 branch?

**Comment by loudnate** [comment]
Yep

**Comment by loudnate** [comment]
Remaining: 
* Storing and uploading: #128 
* Using as insulin data with user preference: 26e1affa8bf2cb04aea7d0c8c01df35956e8d750
