### ISSUE TITLE
Enact temps immediately

### ISSUE THREAD

**Issue by scottleibrand** [loudnate/Loop#32]
With the current timing of RL heartbeats and Share polling, the Loop app sits with a new Recommended Basal for 4 minutes before enacting it. It should instead do an enact immediately after generating the recommendation.

**Comment by loudnate** [comment]
Ah yes, in the G4 + x22 case, it's not executing the BG polling and pump polling in a deterministic order: https://github.com/loudnate/Loop/blob/master/Loop/Managers/DeviceDataManager.swift#L85-L89

That should be changed.
