### ISSUE TITLE
Maximum bolus is ignored

### ISSUE THREAD

**Issue by scottleibrand** [loudnate/Loop#33]
I have maximum bolus in Loop set to 1U (and 6U on the pump itself) and was just able to do a 1.5U bolus from Loop.

**Comment by CrushingT1D** [comment]
I tested this by setting my max to 0.1u in app and giving myself a 0.2u bolus and it gave the bolus as well.

**Comment by loudnate** [comment]
Yep – `maxBolus` is never used... 😊 https://github.com/loudnate/Loop/blob/master/Loop/Managers/DoseMath.swift#L131

**Comment by amazaheri** [comment]
Related to this would be great to validate carb entry, yesterday Sam by mistake keyed 5523 gr vs 55 and Loop suggested 553 units.
