### ISSUE TITLE
Disabling closed loop doesn't stop "loop not working" notifications

### ISSUE THREAD

**Issue by danamlewis** [loudnate/Loop#36]
Disabling the closed loop (toggling the button off) still yields "loop not working" notifications. Notifications also still occur even if the Rileylink is toggled off.

**Comment by loudnate** [comment]
I think it's useful to still receive notifications of connection errors while "open looping". 
One way to clearly understand the user's intent to stop using the app (without deleting it) might be to detect whether any RileyLink devices are configured to auto-connect, which is the switch displayed next to each device.
When there are no devices configured (all the switches are off), we can cancel any scheduled in-flight failure notifications.

**Comment by scottleibrand** [comment]
Yeah, that would work well.
