### ISSUE TITLE
Request for Enlight cgm support

### ISSUE THREAD

**Issue by billstackpole** [loudnate/Loop#40]
Would like to test on 723 v2.4a with enlight and connect and enlight/RileyLink pairs

**Comment by loudnate** [comment]
Bill, do you have a RileyLink so you can test this feature?

**Comment by ps2** [comment]
Let me know if you have issues with this.  The NS uploader does attempt to take BG data from mysentry packets and upload them to NS entries.  It used to work back when we were using it, but a lot of code has changed, and I haven't tested it recently.

**Comment by billstackpole** [comment]
Yes - more than one in case one fails.
