### ISSUE TITLE
A52 error

### ISSUE THREAD

**Issue by eyim** [loudnate/Loop#58]
When attempting a bolus this evening through the app, the pump gave a A52 error and reset - counted from 1 to 7 and then restarted.  Upon restart the time was wiped out, the pump stopped working, and it said I needed to rewind.  After rewinding and redoing the reservoir, the pump seems fine.  This is actually the second time this has happened.  The first time, I didn't log an issue as I thought it was just something random.  But this is the second time this has happened while using the Loop.  

According to this random internet post http://www.diabetesforums.com/forum/topic/51722-mlnimed-revel-error-a52/  - an A52 error is a software safety check as a result of the bolus error.

We have never gotten this error before using openAPS which seems logical since it doesn't do boluses.

**Comment by loudnate** [comment]
This ticket isn't the right place for it, but I do think the broader community should start a collaborative effort to document the errors we've seen. (I had an A64 error on April 26 at 10:00 AM, but not since.)

Unless you think there might be something wrong with the remote command itself? Can you reproduce the error by sending the same bolus?

Without more info, I'd assume this is a safety check related to the motor movement itself, not the remote command.

**Comment by eyim** [comment]
At this point it is unclear what is causing the issue and will likely be difficult to pinpoint. It has only happened so far when issuing a bolus command from Loop but doesn't happen frequently enough to pin point the root cause.  My gut says maybe something in the communication layer talking to the pump but nothing hard to go on yet.  

I'll continue testing and let you know if I find anything else.  I felt it was worth reporting here as this is one of the few implementations where the bolus command is used extensively.

**Comment by eyim** [comment]
Okay was able to reproduce the error.  Basically, what happens is if you send a bolus command to the pump and then attempt to manually (on the pump) deliver a bolus while that command from the Loop arrives.  So you are in the bolus wizard on the pump when it received the command from the Loop  

There are several ways this happens for us:

1) The bolus command from the pump is sent but we get an error that "the bolus may have failed"  So my son as a backup goes into the pump to give himself insulin
2) We try to issue the bolus through Loop but for whatever reason it takes longer than normal to how up on the pump (right now we always double check that the bolus was given).  Because of the delay, my son attempts to give the bolus through the pump.

In either case, an A52 error results.

**Comment by loudnate** [comment]
Interesting. Did you know you can swipe left (or pull down, if the phone is unlocked) on the notification to quickly retry the bolus?
With iOS 10 this fall, the retry action will be available inside the app, too.

I'm not sure there's a software fix we can make for those use cases, other than a warning to "don't try to bolus remotely and using the bolus wizard". Is there anything you'd suggest?

cc @bewest – this is right up there with the "bolus while suspended" glitch.

**Comment by eyim** [comment]
I didn't know that retry action tip.  Thanks for the info.

I also agree with you that I don't think this is a software fix that can be taken care of with your Loop.  We would need to find a command that returned the current status screen of the pump which I find highly unlikely. 

I think the best thing we can do is a big warning on the wiki about it so that people avoid it.  At least now we know what is causing it.

**Comment by scottleibrand** [comment]
Could you check the bolusing status and then send an the escape key before sending the bolus?

**Comment by loudnate** [comment]
That doesn't solve the underlying problem - a race condition between the pump waking, and a user using the menus. 

Also, @eyim said:
> It doesn't have to already be giving the insulin. Simply being in the bolus wizard menu process will cause it

**Comment by loudnate** [comment]
I've also confirmed on my pump that sending a remote bolus while the pump is already bolusing doesn't lead to the A52 error, the remote command correctly fails.

**Comment by scottleibrand** [comment]
Right, the Esc would only be issued if there wasn't a bolus running, to cancel out of any bolus wizard menus before issuing a bolus.

**Comment by shanselman** [comment]
Just wanted to chime in as a confirmation and FYI. I hit this today while I was in the Bolus wizard checking my IOB when a Remote Bolus was issued (also by me, multitasking) from Loop.

**Comment by bewest** [comment]
Including medtronic in "the loop."
