### ISSUE TITLE
StatusChartHighlightLayer build error

### ISSUE THREAD

**Issue by CrushingT1D** [loudnate/Loop#67]
Xcode Version 7.3 (7D175)
Recreate: download direct from Loop/Master and build

Error in StatusChartManager.swift
Lines 267,346,414,482

![image](https://cloud.githubusercontent.com/assets/18058098/16711121/6559a30e-468e-11e6-9210-74a5493fc135.png)

I've seen similar errors pop up in other projects with the newest version of swift.

**Comment by loudnate** [comment]
I checked out a fresh copy of the repository and everything builds correctly using Xcode 7.3.1. I'm assuming updating will fix the issue.
