### ISSUE TITLE
Add Trend and Direction to Loop Graphic

### ISSUE THREAD

**Issue by jlucasvt** [loudnate/Loop#72]
Add the Current Glucose Reading Value and Trend Direction to the Loop open/closed Graphic. I know it's on the watch app but it would be great to have it at the top of the main app as well.

<img width="611" alt="screen shot 2016-07-17 at 2 14 55 pm" src="https://cloud.githubusercontent.com/assets/19819388/16902283/f39d4c2a-4c28-11e6-80e9-0a558a8b4fde.png">

**Comment by loudnate** [comment]
Thanks for drawing this up, but this is the sort of thing that's better for you to track/implement in your own fork, and propose back in a pull request when you feel like it's a necessary baseline contribution. 

Loop won't ever be the single UX for everybody's needs, rather, it's an example template that can be used for finer customization. YDMV, and I hope this project makes it easy to focus on the Vary part, and not have to worry about the lowest-common denominator boilerplate.

**Comment by jlucasvt** [comment]
Will do. Thanks Nate
