### ISSUE TITLE
mlab setup placeholder

### ISSUE THREAD

**Issue by CrushingT1D** [loudnate/Loop#79]
The use of 'nightscoutdb' is a little confusing in MLabService.swift  (LN:24).
I am not sure what to put in here and it may confused people that it is related to nightscout.

I've attempted to use my mLabAPIPath from the old RemoteSettings (without the leading database/) but I continue to get a ConnectionError

**Comment by loudnate** [comment]
Did you get it working? That database name is the best name I could think of; what would you suggest?

I still plan to remove mLab support in favor of using the nightscout API, but there's a number of things to address first.

**Comment by jlucasvt** [comment]
I created a wiki with instructions.  https://github.com/loudnate/Loop/wiki/Setup-mLab-Logging
Database is the correct name.  The instructions are pretty detailed.

**Comment by CrushingT1D** [comment]
I had to generate a new key in mlab to get this to work after upgrading Loop.
