### ISSUE TITLE
Bolus 'Wizard'

### ISSUE THREAD

**Issue by apabari** [loudnate/Loop#86]
Enhancement Request:

Would it be possible to add a Bolus Wizard, where the user is prompted to input carbs and fibre, and a recommendation is made on Bolus amount based on... 
- current I:C ratio
- current basal rate
- current IOB

Long-term would be ideal to link to an online food database, or provide the user with opportunity to add 'favourite' meals.

**Comment by loudnate** [comment]
This is already how Loop should be working. After entering carbs, a recommended bolus will appear. In addition, any time the bolus screen is launched, it should suggest a bolus amount. 

Meal databases are way out scope for this app. However, any other apps that enter carbs into HealthKit can be used with Loop.
