### ISSUE TITLE
Collapse sensor data into a HUD element

### ISSUE THREAD

**Issue by loudnate** [loudnate/Loop#97]
Taking cues from an early modification by @crushingt1d, putting the last glucose value into a HUD element (I think I prefer second-from-leading). 

Compactly this can describe the last glucose value, the trend arrow, the calibration state and the time, enabling the further removal of the text-based rows at the bottom that cause so much anxiety.

**Comment by jlucasvt** [comment]
This would be a great addition. I have found that adding this to the HUD is very helpful when using Loop.  I am assuming Loop status would continue to be leading.
