### ISSUE TITLE
Device identifier for Nightscout

### ISSUE THREAD

**Issue by loudnate** [loudnate/Loop#98]
How should the device identifier be constructed for Nightscout?

cc @ps2

**Comment by ps2** [comment]
There are several device identifiers, and I don't think we need to squash them into a single string. 
  * We'll add pumpID to the events.  
  * The `device` field of `devicestatus.json` has been historically used to identify the 'rig' doing the uploading.  I think in this case it would make sense to use the phone's name. 
  * I'd like to track RileyLink ids (and maybe some connection status info) on the devicestatus upload as well. I think this could go into a new object on devicestatus and maybe new nightscout plugin if needed.
  * The app id I think makes sense as a new field in the `uploader` object on devicestatus.  Could display this in the hover for the uploader pill.  Version probably also makes sense here.

**Comment by loudnate** [comment]
(should have read this one first!)

These all sound good; Nightscout is still out of my purview. Thoughts:
* We can refactor the Bundle Name + Marketing Version string creation out of `SettingsTableViewController` and use it both places.
* Is RileyLink ID the name? or something else?

**Comment by ps2** [comment]
Sounds good on bundle name + version refactoring.
Yes, RL id is the RL name.

**Comment by loudnate** [comment]
Perfect. I'm going to put together https://github.com/loudnate/LoopKit/issues/48 right now, and revisit this ticket when its time to integrate the framework changes

**Comment by loudnate** [comment]
After discussion, we went with `loop://\(CFBundleName)`
